name: release-CI

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Quay IO
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
    
      - name: Build docker image and push to quay.io
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: quay.io/arash77/whisperx:${{ github.event.release.tag_name }}


